<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Penduduk;

class PendudukSeeder extends Seeder
{
    public function run(): void
    {
        $dataPenduduk = [
            // KK 1 - Keluarga Ahmad (Dusun Padaelo)
            [
                'nik' => '7371010101850001',
                'no_kk' => '7371010101850001',
                'nama' => 'Ahmad Syahrul',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1985-03-15',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'PNS',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Merdeka No. 10',
                'rt' => '001',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371010101880002',
                'no_kk' => '7371010101850001',
                'nama' => 'Siti Rahmawati',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1988-07-22',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Merdeka No. 10',
                'rt' => '001',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371010101100003',
                'no_kk' => '7371010101850001',
                'nama' => 'Muhammad Farhan',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2010-05-10',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Merdeka No. 10',
                'rt' => '001',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371010101150004',
                'no_kk' => '7371010101850001',
                'nama' => 'Aisyah Putri',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2015-11-20',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Merdeka No. 10',
                'rt' => '001',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // KK 2 - Keluarga Budi (Dusun Padaelo)
            [
                'nik' => '7371010201750005',
                'no_kk' => '7371010201750005',
                'nama' => 'Budi Santoso',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1975-08-05',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Pertanian No. 5',
                'rt' => '002',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371010201780006',
                'no_kk' => '7371010201750005',
                'nama' => 'Dewi Lestari',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1978-12-10',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Pertanian No. 5',
                'rt' => '002',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371010201000007',
                'no_kk' => '7371010201750005',
                'nama' => 'Rizky Pratama',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2000-04-18',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Pertanian No. 5',
                'rt' => '002',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // KK 3 - Keluarga Darmawan (Dusun Empang)
            [
                'nik' => '7371010301800008',
                'no_kk' => '7371010301800008',
                'nama' => 'Darmawan Putra',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1980-01-25',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'D3',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Nelayan No. 8',
                'rt' => '001',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371010301830009',
                'no_kk' => '7371010301800008',
                'nama' => 'Nurul Hidayah',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1983-06-14',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Nelayan No. 8',
                'rt' => '001',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371010301080010',
                'no_kk' => '7371010301800008',
                'nama' => 'Anisa Zahra',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2008-09-30',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Nelayan No. 8',
                'rt' => '001',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // KK 4 - Keluarga Hendra (Dusun Empang)
            [
                'nik' => '7371010401700011',
                'no_kk' => '7371010401700011',
                'nama' => 'Hendra Wijaya',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1970-02-28',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Nelayan',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Pantai No. 12',
                'rt' => '002',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371010401720012',
                'no_kk' => '7371010401700011',
                'nama' => 'Fatimah',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1972-11-05',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'Tidak Tamat SD',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Pantai No. 12',
                'rt' => '002',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371010401950013',
                'no_kk' => '7371010401700011',
                'nama' => 'Agus Salim',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1995-07-12',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Buruh',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Pantai No. 12',
                'rt' => '002',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // KK 5 - Keluarga Rudi (Dusun Padaelo) - Cerai
            [
                'nik' => '7371010501650014',
                'no_kk' => '7371010501650014',
                'nama' => 'Rudi Hartono',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1965-04-08',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Pensiunan',
                'status_perkawinan' => 'Cerai Hidup',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Kenanga No. 3',
                'rt' => '003',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],

            // Single - Penduduk Lajang (Dusun Padaelo)
            [
                'nik' => '7371010601900015',
                'no_kk' => '7371010601900015',
                'nama' => 'Andi Saputra',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1990-10-17',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'S2',
                'pekerjaan' => 'Karyawan Swasta',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Melati No. 7',
                'rt' => '001',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],

            // KK 6 - Keluarga Herman (Dusun Padaelo) - Janda
            [
                'nik' => '7371010701550016',
                'no_kk' => '7371010701550016',
                'nama' => 'Mariam',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1955-03-20',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'Tidak/Belum Sekolah',
                'pekerjaan' => 'Belum/Tidak Bekerja',
                'status_perkawinan' => 'Cerai Mati',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Anggrek No. 15',
                'rt' => '003',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],

            // KK 7 - Keluarga Sulaiman (Dusun Empang)
            [
                'nik' => '7371010801820017',
                'no_kk' => '7371010801820017',
                'nama' => 'Sulaiman',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1982-08-11',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Mawar No. 9',
                'rt' => '001',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371010801850018',
                'no_kk' => '7371010801820017',
                'nama' => 'Kartini',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1985-04-21',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Mawar No. 9',
                'rt' => '001',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371010801180019',
                'no_kk' => '7371010801820017',
                'nama' => 'Fauzan',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2018-02-14',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'Tidak/Belum Sekolah',
                'pekerjaan' => 'Belum/Tidak Bekerja',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Mawar No. 9',
                'rt' => '001',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371010801200020',
                'no_kk' => '7371010801820017',
                'nama' => 'Nabila',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2020-12-25',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'Tidak/Belum Sekolah',
                'pekerjaan' => 'Belum/Tidak Bekerja',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Mawar No. 9',
                'rt' => '001',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // Data Random Tambahan (20 data)
            // KK 8 - Keluarga Joko (Dusun Padaelo)
            [
                'nik' => '7371010901870021',
                'no_kk' => '7371010901870021',
                'nama' => 'Joko Widodo',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1987-06-15',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Karyawan Swasta',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Sudirman No. 20',
                'rt' => '004',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371010901890022',
                'no_kk' => '7371010901870021',
                'nama' => 'Sari Dewi',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1989-09-22',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Sudirman No. 20',
                'rt' => '004',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // KK 9 - Keluarga Eko (Dusun Empang)
            [
                'nik' => '7371011001790023',
                'no_kk' => '7371011001790023',
                'nama' => 'Eko Prasetyo',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1979-03-08',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Diponegoro No. 15',
                'rt' => '003',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011001810024',
                'no_kk' => '7371011001790023',
                'nama' => 'Ratna Sari',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1981-11-30',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Diponegoro No. 15',
                'rt' => '003',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371011001120025',
                'no_kk' => '7371011001790023',
                'nama' => 'Dika Pratama',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2012-05-18',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Diponegoro No. 15',
                'rt' => '003',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // KK 10 - Keluarga Agus (Dusun Padaelo)
            [
                'nik' => '7371011101840026',
                'no_kk' => '7371011101840026',
                'nama' => 'Agus Setiawan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-07-25',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'D3',
                'pekerjaan' => 'PNS',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Gatot Subroto No. 5',
                'rt' => '005',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011101860027',
                'no_kk' => '7371011101840026',
                'nama' => 'Indah Permata',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1986-12-10',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'PNS',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Gatot Subroto No. 5',
                'rt' => '005',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // Single - Lajang (Dusun Empang)
            [
                'nik' => '7371011201920028',
                'no_kk' => '7371011201920028',
                'nama' => 'Rina Wulandari',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1992-04-14',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Karyawan Swasta',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Ahmad Yani No. 8',
                'rt' => '004',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],

            // KK 11 - Keluarga Bambang (Dusun Padaelo)
            [
                'nik' => '7371011301770029',
                'no_kk' => '7371011301770029',
                'nama' => 'Bambang Sutrisno',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1977-01-20',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Sawah No. 12',
                'rt' => '006',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011301800030',
                'no_kk' => '7371011301770029',
                'nama' => 'Siti Nurhaliza',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1980-08-05',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Sawah No. 12',
                'rt' => '006',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371011301030031',
                'no_kk' => '7371011301770029',
                'nama' => 'Rizki Maulana',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2003-10-12',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Sawah No. 12',
                'rt' => '006',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // KK 12 - Keluarga Dedi (Dusun Empang)
            [
                'nik' => '7371011401880032',
                'no_kk' => '7371011401880032',
                'nama' => 'Dedi Kurniawan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1988-02-28',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Pasar No. 25',
                'rt' => '005',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011401900033',
                'no_kk' => '7371011401880032',
                'nama' => 'Lina Marlina',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1990-06-15',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Pasar No. 25',
                'rt' => '005',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // Single - Lajang (Dusun Padaelo)
            [
                'nik' => '7371011501930034',
                'no_kk' => '7371011501930034',
                'nama' => 'Fajar Nugroho',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1993-09-08',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Cendana No. 11',
                'rt' => '007',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],

            // KK 13 - Keluarga Tono (Dusun Empang)
            [
                'nik' => '7371011601760035',
                'no_kk' => '7371011601760035',
                'nama' => 'Tono Wijaya',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1976-11-22',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Nelayan',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Pantai Indah No. 3',
                'rt' => '006',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011601780036',
                'no_kk' => '7371011601760035',
                'nama' => 'Siti Aisyah',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1978-03-17',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'Tidak Tamat SD',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Pantai Indah No. 3',
                'rt' => '006',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371011601050037',
                'no_kk' => '7371011601760035',
                'nama' => 'Ahmad Fauzi',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2005-07-30',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Pantai Indah No. 3',
                'rt' => '006',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // KK 14 - Keluarga Yanto (Dusun Padaelo)
            [
                'nik' => '7371011701830038',
                'no_kk' => '7371011701830038',
                'nama' => 'Yanto Susilo',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1983-05-19',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Buruh',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Merpati No. 18',
                'rt' => '008',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011701850039',
                'no_kk' => '7371011701830038',
                'nama' => 'Maya Sari',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1985-12-03',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Merpati No. 18',
                'rt' => '008',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // Single - Lajang (Dusun Empang)
            [
                'nik' => '7371011801910040',
                'no_kk' => '7371011801910040',
                'nama' => 'Putri Ayu',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1991-08-25',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Dokter',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Kesehatan No. 7',
                'rt' => '007',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
        ];

        foreach ($dataPenduduk as $data) {
            Penduduk::create($data);
        }
    }
}
