<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Penduduk;

class PendudukSeederTambah extends Seeder
{
    public function run(): void
    {
        $dataPenduduk = [
            // Data Random Tambahan (20 data)
            // KK 8 - Keluarga Joko (Dusun Padaelo)
            [
                'nik' => '7371010901870021',
                'no_kk' => '7371010901870021',
                'nama' => 'Joko Widodo',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1987-06-15',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Karyawan Swasta',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Sudirman No. 20',
                'rt' => '004',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371010901890022',
                'no_kk' => '7371010901870021',
                'nama' => 'Sari Dewi',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1989-09-22',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Sudirman No. 20',
                'rt' => '004',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // KK 9 - Keluarga Eko (Dusun Empang)
            [
                'nik' => '7371011001790023',
                'no_kk' => '7371011001790023',
                'nama' => 'Eko Prasetyo',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1979-03-08',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Diponegoro No. 15',
                'rt' => '003',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011001810024',
                'no_kk' => '7371011001790023',
                'nama' => 'Ratna Sari',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1981-11-30',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Diponegoro No. 15',
                'rt' => '003',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371011001120025',
                'no_kk' => '7371011001790023',
                'nama' => 'Dika Pratama',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2012-05-18',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Diponegoro No. 15',
                'rt' => '003',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // KK 10 - Keluarga Agus (Dusun Padaelo)
            [
                'nik' => '7371011101840026',
                'no_kk' => '7371011101840026',
                'nama' => 'Agus Setiawan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-07-25',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'D3',
                'pekerjaan' => 'PNS',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Gatot Subroto No. 5',
                'rt' => '005',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011101860027',
                'no_kk' => '7371011101840026',
                'nama' => 'Indah Permata',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1986-12-10',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'PNS',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Gatot Subroto No. 5',
                'rt' => '005',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // Single - Lajang (Dusun Empang)
            [
                'nik' => '7371011201920028',
                'no_kk' => '7371011201920028',
                'nama' => 'Rina Wulandari',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1992-04-14',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Karyawan Swasta',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Ahmad Yani No. 8',
                'rt' => '004',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],

            // KK 11 - Keluarga Bambang (Dusun Padaelo)
            [
                'nik' => '7371011301770029',
                'no_kk' => '7371011301770029',
                'nama' => 'Bambang Sutrisno',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1977-01-20',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Sawah No. 12',
                'rt' => '006',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011301800030',
                'no_kk' => '7371011301770029',
                'nama' => 'Siti Nurhaliza',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1980-08-05',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Sawah No. 12',
                'rt' => '006',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371011301030031',
                'no_kk' => '7371011301770029',
                'nama' => 'Rizki Maulana',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2003-10-12',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Sawah No. 12',
                'rt' => '006',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // KK 12 - Keluarga Dedi (Dusun Empang)
            [
                'nik' => '7371011401880032',
                'no_kk' => '7371011401880032',
                'nama' => 'Dedi Kurniawan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1988-02-28',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Pasar No. 25',
                'rt' => '005',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011401900033',
                'no_kk' => '7371011401880032',
                'nama' => 'Lina Marlina',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1990-06-15',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Pasar No. 25',
                'rt' => '005',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // Single - Lajang (Dusun Padaelo)
            [
                'nik' => '7371011501930034',
                'no_kk' => '7371011501930034',
                'nama' => 'Fajar Nugroho',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1993-09-08',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Cendana No. 11',
                'rt' => '007',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],

            // KK 13 - Keluarga Tono (Dusun Empang)
            [
                'nik' => '7371011601760035',
                'no_kk' => '7371011601760035',
                'nama' => 'Tono Wijaya',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1976-11-22',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SD/Sederajat',
                'pekerjaan' => 'Nelayan',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Pantai Indah No. 3',
                'rt' => '006',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011601780036',
                'no_kk' => '7371011601760035',
                'nama' => 'Siti Aisyah',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1978-03-17',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'Tidak Tamat SD',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Pantai Indah No. 3',
                'rt' => '006',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],
            [
                'nik' => '7371011601050037',
                'no_kk' => '7371011601760035',
                'nama' => 'Ahmad Fauzi',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2005-07-30',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Anak',
                'alamat' => 'Jl. Pantai Indah No. 3',
                'rt' => '006',
                'rw' => '002',
                'is_kepala_keluarga' => false,
            ],

            // KK 14 - Keluarga Yanto (Dusun Padaelo)
            [
                'nik' => '7371011701830038',
                'no_kk' => '7371011701830038',
                'nama' => 'Yanto Susilo',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1983-05-19',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Buruh',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Merpati No. 18',
                'rt' => '008',
                'rw' => '001',
                'is_kepala_keluarga' => true,
            ],
            [
                'nik' => '7371011701850039',
                'no_kk' => '7371011701830038',
                'nama' => 'Maya Sari',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1985-12-03',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Padaelo',
                'status_dalam_keluarga' => 'Istri',
                'alamat' => 'Jl. Merpati No. 18',
                'rt' => '008',
                'rw' => '001',
                'is_kepala_keluarga' => false,
            ],

            // Single - Lajang (Dusun Empang)
            [
                'nik' => '7371011801910040',
                'no_kk' => '7371011801910040',
                'nama' => 'Putri Ayu',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1991-08-25',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'pendidikan' => 'S1/D4',
                'pekerjaan' => 'Dokter',
                'status_perkawinan' => 'Belum Kawin',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Empang',
                'status_dalam_keluarga' => 'Kepala Keluarga',
                'alamat' => 'Jl. Kesehatan No. 7',
                'rt' => '007',
                'rw' => '002',
                'is_kepala_keluarga' => true,
            ],
        ];

        foreach ($dataPenduduk as $data) {
            // Skip if NIK already exists
            if (!Penduduk::where('nik', $data['nik'])->exists()) {
                Penduduk::create($data);
            }
        }
    }
}
